'use strict';

const { query } = require('./index');

const CHECKS = [
  // ── QUARTERLY ──────────────────────────────────────────────────────────────
  {
    name: 'External ASV Vulnerability Scan',
    description: 'Quarterly external vulnerability scan performed by a PCI SSC Approved Scanning Vendor (ASV). Must result in a passing scan report.',
    instructions: '1. Engage your ASV to schedule the scan.\n2. Remediate all findings.\n3. Obtain passing ASV report.\n4. Upload report and remediation evidence.',
    cadence: 'quarterly',
    pci_req_refs: ['11.3.2'],
    required_evidence_labels: ['Passing ASV Report', 'Remediation Evidence', 'ASV Attestation'],
    conditional_on: null,
    sort_order: 10,
  },
  {
    name: 'Internal Vulnerability Scan',
    description: 'Quarterly authenticated internal vulnerability scan. High-risk and critical vulnerabilities must be remediated and rescanned.',
    instructions: '1. Run authenticated scan against all in-scope internal systems.\n2. Risk-rank all findings per Req 6.3.1.\n3. Remediate high/critical findings.\n4. Rescan to confirm remediation.\n5. Upload scan report and rescan results.',
    cadence: 'quarterly',
    pci_req_refs: ['11.3.1'],
    required_evidence_labels: ['Scan Report', 'Risk-Ranked Findings', 'Rescan Confirmation'],
    conditional_on: null,
    sort_order: 20,
  },
  {
    name: 'Wireless Scan — Rogue AP Detection',
    description: 'Quarterly scan for unauthorized wireless access points in or near the CDE. All unauthorized APs must be investigated and resolved.',
    instructions: '1. Conduct wireless scan of CDE and surrounding areas.\n2. Compare detected APs against authorized AP inventory.\n3. Investigate any unauthorized APs.\n4. Confirm AP inventory is current.\n5. Upload scan results.',
    cadence: 'quarterly',
    pci_req_refs: ['11.2.1'],
    required_evidence_labels: ['Wireless Scan Results', 'AP Inventory', 'Unauthorized AP Resolution Evidence'],
    conditional_on: 'has_wireless_in_cde',
    sort_order: 30,
  },
  {
    name: 'Third-Party / Remote Access Account Review',
    description: 'Quarterly review of all third-party and vendor remote access accounts. Accounts must be enabled only when needed and disabled when not in use.',
    instructions: '1. Pull list of all third-party/vendor remote access accounts.\n2. Confirm each account is still needed and active.\n3. Disable or remove any terminated or unused accounts.\n4. Document review and upload sign-off.',
    cadence: 'quarterly',
    pci_req_refs: ['8.2.7'],
    required_evidence_labels: ['Account List', 'Review Sign-off', 'Removed/Disabled Accounts Log'],
    conditional_on: null,
    sort_order: 40,
  },
  {
    name: 'Payment Page Integrity Attestation',
    description: 'Quarterly attestation that the continuous payment page change/tamper detection mechanism was active all quarter and all alerts were investigated.',
    instructions: '1. Export monitoring tool output for the quarter.\n2. Confirm all alerts were investigated and resolved.\n3. Confirm no unauthorized script changes occurred.\n4. Upload monitoring output and sign-off.',
    cadence: 'quarterly',
    pci_req_refs: ['11.6.1'],
    required_evidence_labels: ['Monitoring Tool Output', 'Alert Investigation Log', 'Quarterly Sign-off'],
    conditional_on: 'has_ecommerce',
    sort_order: 50,
  },
  {
    name: 'Log Review Process Attestation',
    description: 'Quarterly attestation that daily log review was performed all quarter, SIEM/alerting rules are current, and all alerts were investigated.',
    instructions: '1. Confirm log collection was active and uninterrupted all quarter.\n2. Review SIEM rule inventory — confirm rules are current.\n3. Document all alerts triggered and investigations performed.\n4. Confirm no gaps in coverage.\n5. Upload attestation and evidence.',
    cadence: 'quarterly',
    pci_req_refs: ['10.4.1', '10.4.1.1'],
    required_evidence_labels: ['SIEM Alert Summary', 'Rule Inventory', 'Investigation Log', 'Quarterly Sign-off'],
    conditional_on: null,
    sort_order: 60,
  },

  // ── SEMI-ANNUAL ────────────────────────────────────────────────────────────
  {
    name: 'NSC / Firewall Configuration Review',
    description: 'Semi-annual review of all NSC (firewall, router) configurations to confirm rules are relevant, effective, and have documented business justification.',
    instructions: '1. Export current ruleset from all in-scope firewalls/routers.\n2. Review each rule — confirm business justification exists.\n3. Remove or disable rules with no current justification.\n4. Document review and sign off.\n5. Upload ruleset export and sign-off.',
    cadence: 'semi_annual',
    pci_req_refs: ['1.2.7'],
    required_evidence_labels: ['Ruleset Export', 'Review Sign-off', 'Removed Rules Log'],
    conditional_on: null,
    sort_order: 110,
  },
  {
    name: 'WAF Rule Review',
    description: 'Semi-annual review of WAF rules and configurations to confirm effectiveness, remove unused rules, and review false positive patterns.',
    instructions: '1. Export WAF configuration and active rule set.\n2. Review rule effectiveness — check false positive rates.\n3. Remove or tune unused or overly broad rules.\n4. Upload configuration export and sign-off.',
    cadence: 'semi_annual',
    pci_req_refs: ['1.2.7', '6.4.1', '6.4.2'],
    required_evidence_labels: ['WAF Config Export', 'Rule Effectiveness Review', 'Sign-off'],
    conditional_on: 'has_waf',
    sort_order: 120,
  },
  {
    name: 'Cloud NSG / Security Group Review',
    description: 'Semi-annual review of cloud network security groups (Azure NSGs, AWS Security Groups, GCP firewall rules) to confirm rules are justified and least-privilege.',
    instructions: '1. Export all NSG/security group rules from cloud environment.\n2. Review each rule — confirm business justification and least privilege.\n3. Remove or restrict overly permissive rules.\n4. Upload export and sign-off.',
    cadence: 'semi_annual',
    pci_req_refs: ['1.2.7', '1.3.2'],
    required_evidence_labels: ['NSG Export', 'Review Sign-off', 'Remediated Rules Log'],
    conditional_on: 'has_cloud_infra',
    sort_order: 130,
  },
  {
    name: 'All User Account Access Review',
    description: 'Semi-annual review of all user accounts and access privileges including third-party/vendor accounts. Management must acknowledge access remains appropriate.',
    instructions: '1. Pull full user + vendor account list with assigned privileges.\n2. Review each account — confirm access matches current job function.\n3. Remove or modify inappropriate access.\n4. Obtain management acknowledgment sign-off.\n5. Upload account list and acknowledgment.',
    cadence: 'semi_annual',
    pci_req_refs: ['7.2.4'],
    required_evidence_labels: ['User Account List', 'Review Sign-off', 'Access Changes Log', 'Management Acknowledgment'],
    conditional_on: null,
    sort_order: 140,
  },
  {
    name: 'CDE Scoping Review & Attestation',
    description: 'Semi-annual confirmation that the CDE boundary is accurate, data flows are current, and any scope changes are documented. Mandatory semi-annual for service providers (12.5.2.1).',
    instructions: '1. Review current scoping diagram and data flow documentation.\n2. Confirm CDE boundary is accurate — no undocumented systems in scope.\n3. Document any scope changes since last review.\n4. Sign off and upload updated documentation.',
    cadence: 'semi_annual',
    pci_req_refs: ['12.5.2', '12.5.2.1'],
    required_evidence_labels: ['Scoping Diagram', 'Data Flow Diagram', 'Scope Changes Log', 'Sign-off'],
    conditional_on: null,
    sp_cadence_note: 'Req 12.5.2.1: Mandatory semi-annual for service providers.',
    sort_order: 150,
  },
  {
    name: 'TPSP Scoping Analysis',
    description: 'Semi-annual review of all third-party service providers — confirm which ones touch CHD, review responsibility matrices, and confirm agreements are current.',
    instructions: '1. Review TPSP inventory (Req 12.8.1).\n2. Confirm data flow per TPSP — which ones touch CHD/SAD.\n3. Review responsibility matrix per TPSP (Req 12.8.5).\n4. Confirm written agreements are in place (Req 12.8.2).\n5. Upload TPSP inventory and responsibility matrix.',
    cadence: 'semi_annual',
    pci_req_refs: ['12.8.1', '12.8.2', '12.8.5'],
    required_evidence_labels: ['TPSP Inventory', 'Responsibility Matrix', 'Agreement Review Confirmation'],
    conditional_on: null,
    sort_order: 160,
  },
  {
    name: 'Encryption at Rest Review & Attestation',
    description: 'Semi-annual attestation that PAN is properly encrypted at rest across all storage locations. Disk-level encryption does NOT satisfy this requirement.',
    instructions: '1. Confirm database TDE or column-level encryption is enabled and configured correctly.\n2. Confirm PAN in files is PGP-encrypted or equivalent.\n3. Confirm backup encryption uses a separate key.\n4. Verify PAN masking on all display surfaces.\n5. Review active unmasking authorizations — confirm business justification on file.\n6. Confirm key management procedures are current.\n7. Upload configuration evidence and sign-off.\n\nNOTE: Disk-level encryption (BitLocker, Azure Disk Encryption, EBS) does NOT satisfy Req 3.4.1.',
    cadence: 'semi_annual',
    pci_req_refs: ['3.4.1', '3.5.1'],
    required_evidence_labels: ['Database Encryption Config', 'File Encryption Inventory', 'Backup Encryption Confirmation', 'Masking Verification', 'Unmasking Authorizations', 'Key Custodian List'],
    conditional_on: null,
    sort_order: 170,
  },
  {
    name: 'Segmentation Testing (Service Providers Only)',
    description: 'Service provider semi-annual penetration test of segmentation controls to confirm CDE is isolated from all out-of-scope systems.',
    instructions: '1. Scope the segmentation test — all segmentation controls/methods in use.\n2. Perform penetration test per entity defined methodology.\n3. Confirm segmentation controls are operational and effective.\n4. Document tester qualifications and organizational independence.\n5. Upload test results and remediation evidence.',
    cadence: 'semi_annual',
    pci_req_refs: ['11.4.6'],
    required_evidence_labels: ['Pen Test Report', 'Segmentation Confirmation', 'Tester Qualifications', 'Remediation Evidence'],
    conditional_on: 'is_service_provider',
    sort_order: 180,
  },

  // ── ANNUAL ─────────────────────────────────────────────────────────────────
  {
    name: 'Internal Penetration Test',
    description: 'Annual internal penetration test per documented methodology. Must cover full CDE perimeter, all critical systems, and segmentation controls.',
    instructions: '1. Engage qualified internal resource or third party (org independence required).\n2. Scope per documented methodology — full CDE internal perimeter.\n3. Perform test, document all findings.\n4. Remediate exploitable vulnerabilities and retest.\n5. Upload test report and remediation evidence.',
    cadence: 'annual',
    pci_req_refs: ['11.4.2'],
    required_evidence_labels: ['Pen Test Report', 'Methodology Document', 'Remediation Evidence', 'Retest Confirmation', 'Tester Qualifications'],
    conditional_on: null,
    sort_order: 210,
  },
  {
    name: 'External Penetration Test',
    description: 'Annual external penetration test per documented methodology. Must cover exposed external perimeter and critical systems accessible from public networks.',
    instructions: '1. Engage qualified external third party (org independence required).\n2. Scope per documented methodology — full external CDE perimeter.\n3. Perform test, document all findings.\n4. Remediate exploitable vulnerabilities and retest.\n5. Upload test report and remediation evidence.',
    cadence: 'annual',
    pci_req_refs: ['11.4.3'],
    required_evidence_labels: ['Pen Test Report', 'Methodology Document', 'Remediation Evidence', 'Retest Confirmation', 'Tester Qualifications'],
    conditional_on: null,
    sort_order: 220,
  },
  {
    name: 'Segmentation Testing (All Entities)',
    description: 'Annual penetration test of segmentation controls confirming CDE is isolated from all out-of-scope systems. Required for all entities using segmentation.',
    instructions: '1. Scope the test — all segmentation controls and methods in use.\n2. Perform penetration test per entity defined methodology.\n3. Confirm CDE is isolated from all out-of-scope systems.\n4. Upload test results with tester qualifications.',
    cadence: 'annual',
    pci_req_refs: ['11.4.5'],
    required_evidence_labels: ['Pen Test Report', 'Segmentation Confirmation', 'Tester Qualifications'],
    conditional_on: null,
    sp_cadence_note: 'Service providers must also complete semi-annual segmentation testing per 11.4.6.',
    sort_order: 230,
  },
  {
    name: 'Information Security Policy Review',
    description: 'Annual review of the information security policy. Must be updated to reflect changes to business objectives and risk environment.',
    instructions: '1. Review all in-scope security policies.\n2. Update for any changes to business objectives or risk environment.\n3. Confirm version control is maintained.\n4. Distribute to all relevant personnel.\n5. Upload reviewed/updated policy and distribution evidence.',
    cadence: 'annual',
    pci_req_refs: ['12.1.2'],
    required_evidence_labels: ['Updated Policy Document', 'Version History', 'Distribution Evidence'],
    conditional_on: null,
    sort_order: 240,
  },
  {
    name: 'Targeted Risk Assessment',
    description: 'Annual formal risk assessment of the CDE identifying assets, threats, likelihood, and impact. Required for all requirements that allow entity-defined frequency.',
    instructions: '1. Identify assets being protected.\n2. Identify threats and vulnerabilities.\n3. Assess likelihood and impact per threat.\n4. Document treatment decisions.\n5. Review prior year results for continued validity.\n6. Upload risk register and assessment report.',
    cadence: 'annual',
    pci_req_refs: ['12.3.1'],
    required_evidence_labels: ['Risk Register', 'Assessment Report', 'Treatment Decisions', 'Senior Management Sign-off'],
    conditional_on: null,
    sort_order: 250,
  },
  {
    name: 'Security Awareness Training',
    description: 'Annual security awareness training for all personnel with CDE access. Must cover threats, phishing/social engineering, acceptable use, and IR responsibilities.',
    instructions: '1. Deliver training via documented method to all in-scope personnel.\n2. Collect acknowledgment sign-offs from all participants.\n3. Review and update curriculum for new threats (Req 12.6.2).\n4. Upload completion records and curriculum.',
    cadence: 'annual',
    pci_req_refs: ['12.6.2', '12.6.3', '12.6.3.1'],
    required_evidence_labels: ['Training Completion Records', 'Acknowledgment Sign-offs', 'Curriculum Review'],
    conditional_on: null,
    sort_order: 260,
  },
  {
    name: 'IR Plan Review & Distribution',
    description: 'Annual review, update, and redistribution of the Incident Response Plan. All IR personnel must acknowledge receipt.',
    instructions: '1. Review IR plan — update for any changes in environment, personnel, or lessons learned.\n2. Distribute updated plan to all IR personnel.\n3. Collect acknowledgment receipts.\n4. Upload updated plan and distribution evidence.',
    cadence: 'annual',
    pci_req_refs: ['12.10.1'],
    required_evidence_labels: ['Updated IR Plan', 'Distribution List', 'Acknowledgment Receipts'],
    conditional_on: null,
    sort_order: 270,
  },
  {
    name: 'Software Component / SBOM Review',
    description: 'Annual review of all software components and libraries to confirm all are current, supported, and free of known vulnerabilities.',
    instructions: '1. Generate/update software component inventory (SBOM).\n2. Check all components for known vulnerabilities (CVEs).\n3. Confirm no end-of-life components in use without risk acceptance.\n4. Upload component inventory and scan results.',
    cadence: 'annual',
    pci_req_refs: ['6.3.3'],
    required_evidence_labels: ['Software Inventory / SBOM', 'Vulnerability Scan Results', 'EOL Component Review'],
    conditional_on: null,
    sort_order: 280,
  },
  {
    name: 'Cryptographic Cipher Suite & Protocol Review',
    description: 'Annual inventory and review of all cryptographic cipher suites and protocols in use. Monitor for deprecated algorithms and document a response plan.',
    instructions: '1. Document all cipher suites and protocols in use — purpose and location.\n2. Check against current industry guidance for deprecated/weak algorithms.\n3. Document plan to address any upcoming deprecations.\n4. Upload inventory and review.',
    cadence: 'annual',
    pci_req_refs: ['12.3.3'],
    required_evidence_labels: ['Cipher Suite Inventory', 'Deprecation Review', 'Response Plan'],
    conditional_on: null,
    sort_order: 290,
  },
  {
    name: 'Cryptographic Key Management Review',
    description: 'Annual review of cryptographic key inventory, rotation schedules, custodian assignments, and split-knowledge/dual-control verification.',
    instructions: '1. Inventory all active encryption keys.\n2. Confirm rotation schedule is being followed.\n3. Confirm custodians are assigned and documented.\n4. Verify split-knowledge and dual-control for key-encrypting keys.\n5. Upload key inventory and custodian confirmation.',
    cadence: 'annual',
    pci_req_refs: ['3.5.1', '3.7.1', '3.7.4'],
    required_evidence_labels: ['Key Inventory', 'Rotation Log', 'Custodian List', 'Split-Knowledge Confirmation'],
    conditional_on: null,
    sort_order: 300,
  },
  {
    name: 'TPSP Agreement Review',
    description: 'Annual review of all TPSP written agreements to confirm each includes PCI DSS responsibility acknowledgment language.',
    instructions: '1. Review all TPSP agreements.\n2. Confirm each includes written acknowledgment that TPSP is responsible for security of CHD it handles.\n3. Update any missing or outdated agreements.\n4. Upload agreement review log.',
    cadence: 'annual',
    pci_req_refs: ['12.8.2', '12.8.3'],
    required_evidence_labels: ['Agreement Review Log', 'Updated Agreements Evidence'],
    conditional_on: null,
    sort_order: 310,
  },
  {
    name: 'TPSP Compliance Certificate Collection',
    description: 'Annual collection of current AOC or equivalent compliance evidence from all in-scope TPSPs. Track expiry dates.',
    instructions: '1. Request current AOC or compliance evidence from each in-scope TPSP.\n2. Confirm evidence covers the services used.\n3. Track expiry dates — flag any expiring within 90 days.\n4. Upload collected AOCs and expiry tracker.',
    cadence: 'annual',
    pci_req_refs: ['12.8.4'],
    required_evidence_labels: ['TPSP AOC Files', 'Expiry Tracker'],
    conditional_on: null,
    sort_order: 320,
  },
  {
    name: 'Physical Security Review',
    description: 'Annual review of physical access controls, surveillance systems, media inventory, and visitor logs for CDE locations.',
    instructions: '1. Review badge access logs — confirm only authorized personnel have access.\n2. Audit surveillance camera coverage and retention.\n3. Review media inventory — all physical media with CHD accounted for.\n4. Review visitor logs for CDE access.\n5. Upload review sign-off and any remediation.',
    cadence: 'annual',
    pci_req_refs: ['9.1.1', '9.2.1'],
    required_evidence_labels: ['Access Log Review', 'Camera Audit', 'Media Inventory', 'Visitor Log Review', 'Sign-off'],
    conditional_on: null,
    sort_order: 330,
  },
  {
    name: 'MFA Configuration Review',
    description: 'Annual confirmation that MFA is enforced for all non-console CDE access. All exceptions must be documented and remediated.',
    instructions: '1. Review MFA enforcement across all CDE access methods (VPN, admin consoles, cloud portals).\n2. Confirm MFA is active for all non-console access.\n3. Document and remediate any exceptions.\n4. Upload configuration evidence and sign-off.',
    cadence: 'annual',
    pci_req_refs: ['8.4.1', '8.4.2'],
    required_evidence_labels: ['MFA Configuration Evidence', 'Exception Log', 'Sign-off'],
    conditional_on: null,
    sort_order: 340,
  },
  {
    name: 'Application Security Review',
    description: 'Annual review of application security practices including DAST/SAST results, dependency scanning, and code review process effectiveness.',
    instructions: '1. Run DAST against public-facing in-scope applications.\n2. Run SAST / dependency scan on in-house code.\n3. Review code review process — confirm security review gates are in place.\n4. Upload scan results and process review.',
    cadence: 'annual',
    pci_req_refs: ['6.2.4', '6.3.1'],
    required_evidence_labels: ['DAST Results', 'SAST/Dependency Scan', 'Code Review Process Confirmation'],
    conditional_on: null,
    sort_order: 350,
  },
  {
    name: 'Wireless Network Full Security Review',
    description: 'Annual comprehensive review of all wireless networks — authorized AP inventory, security configuration, and unauthorized AP check.',
    instructions: '1. Review authorized AP inventory — confirm current and justified.\n2. Review wireless security configuration (encryption, authentication).\n3. Perform full unauthorized AP scan.\n4. Upload inventory and review results.',
    cadence: 'annual',
    pci_req_refs: ['11.2.1', '11.2.2'],
    required_evidence_labels: ['AP Inventory', 'Security Config Review', 'Unauthorized AP Scan Results'],
    conditional_on: 'has_wireless_in_cde',
    sort_order: 360,
  },
  {
    name: 'Change Control Process Audit',
    description: 'Annual audit of the change control process effectiveness — sample of changes reviewed for compliance with documented procedures.',
    instructions: '1. Sample recent changes (minimum 10 or 10% of changes, whichever is larger).\n2. For each sampled change, verify it followed the change control process.\n3. Document any deviations and remediation.\n4. Upload sample review and findings.',
    cadence: 'annual',
    pci_req_refs: ['6.5.1', '6.5.2'],
    required_evidence_labels: ['Change Sample Review', 'Deviation Log', 'Remediation Evidence'],
    conditional_on: null,
    sort_order: 370,
  },
];

async function seedComplianceChecks() {
  for (const check of CHECKS) {
    const { rows } = await query(
      'SELECT id FROM compliance_check_definitions WHERE name = $1 AND is_builtin = TRUE',
      [check.name]
    );
    if (rows.length > 0) continue;

    await query(
      `INSERT INTO compliance_check_definitions
         (name, description, instructions, cadence, pci_req_refs,
          required_evidence_labels, conditional_on, sp_cadence_note, is_builtin, sort_order)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,TRUE,$9)`,
      [
        check.name, check.description, check.instructions || null,
        check.cadence, check.pci_req_refs, check.required_evidence_labels,
        check.conditional_on || null, check.sp_cadence_note || null, check.sort_order,
      ]
    );
  }
}

module.exports = { seedComplianceChecks };
